# Do not edit. Generated by the configure script.
export PATH:=/srv/cgm-remote-monitor/packages/node/node-v16.20.2/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/usr/bin/python3.10
PREFIX=/usr/local
